server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.2.251:3306/daily?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Xin3291129$

mybatis-plus:
  mapper-locations: classpath:mapper/work/*Mapper.xml